group = com.stevenyang.datadogproactive
version = 0.1.0

pluginRepositoryUrl = https://github.com/stevenyang/jetbrains-hackathon

# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency = false

# Gradle performance
org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.jvmargs = -Xmx2g -XX:MaxMetaspaceSize=512m
